grow_version: ">=0.0.66"
home: /content/amp-dev/index.html

localization:
  root_path: /{locale}/
  default_locale: en
  locales:
  - en
  - de
  - fr
  - it
  - id
  - ja
  - ko
  - ru

markdown:
  extensions:
  - kind: sourcecode
    classes: True
    class_name: ad-m-code-snippet
  - kind: markdown.extensions.codehilite
    classes: True
    class_name: ad-m-code-snippet

ext:
- extensions.amp_dependency_injector.AmpDependencyInjectorExtension
- extensions.inline_text_assets.InlineTextAssetsExtension:
    bundles:
        - name: 'styles'
          method: 'addCssFile'
        - name: 'icons'
          method: 'useIcon'
- extensions.shortcodes.ShortcodesExtension
