language: node_js
node_js:
  - "lts/*"

git:
  depth: 3

cache:
  - pip
  - npm

install:
  - pip install grow==0.6.5 --user
  - grow --version
  - npm ci

before_deploy:
  - npm run build:staging

deploy:
  provider: gae
  keyfile: ".staging-secret.json"
  project: amp-dev-staging
  skip_cleanup: true
  on: 
    branch: future

before_install:
- openssl aes-256-cbc -K $encrypted_d4a09416a845_key -iv $encrypted_d4a09416a845_iv
  -in .staging-secret.json.enc -out .staging-secret.json -d
