home: /content/amp-dev/index.html

localization:
  root_path: /{locale}/
  default_locale: en

sitemap:
  enabled: yes
  path: '/sitemap_grow.xml'
  template: '/layouts/sitemap.xml'

markdown:
  extensions:
  - kind: sourcecode
    classes: True
    class_name: ap-m-code-snippet
  - kind: markdown.extensions.codehilite
    classes: True
    class_name: ap-m-code-snippet
  - kind: markdown.extensions.extra

ext:
- extensions.inline_text_assets.InlineTextAssetsExtension:
    bundles:
        - name: 'styles'
          method: 'addCssFile'
        - name: 'icons'
          method: 'useIcon'
- extensions.amp_example_preview.AmpExamplePreviewExtension
- extensions.amp_dependencies.AmpDependenciesExtension
- extensions.amp_dev.AmpDevExtension
- extensions.url_beautifier.UrlBeautifierExtension
- extensions.internal_links.PodInternalLinkExtension
- extensions.jinja2_optimized_codehilite.Jinja2OptimizedCodehiliteExtension
- extensions.markdown_toc_patch.MarkdownTocPatchExtension
- extensions.markdown_in_html.MarkdownInHtmlExtension:
    prevent_markdown_extra_auto_loading_other: true
