grow_version: ">=0.0.66"
home: /content/amp-dev/index.html

static_dirs:
- static_dir: /static/
  serve_at: /static/

localization:
  root_path: /{locale}/
  default_locale: en

ext:
- extensions.amp_dependency_injector.AmpDependencyInjectorExtension
- extensions.dynamic_css_bundles.DynamicCssBundlesExtension
- extensions.shortcodes.ShortcodesExtension
