---
name: 'Lint: JavaScript'

on:
  push:
    paths:
      - '**/*.js'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Installing Node.js packages
        run: npm ci

      - name: Linting JavaScript files
        run: |
          gulp lintNode
