---
name: 'Test: Platform'

on:
  push:
    paths:
      - 'package.json'
      - 'platform/lib/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing Node.js packages
        run: npm ci

      - name: Running Platform tests
        run: |
          gulp updateTestResources
          npm run test:platform
