---
name: 'Test: Grow'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing Node.js packages
        run: npm ci

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}

      - name: Installing Grow
        run: |
          sudo apt-get install libyaml-dev
          pip install grow --upgrade-strategy eager

      - name: Preparing test resources
        run: |
          gulp buildComponentVersions

      - name: Running Grow tests
        working-directory: /home/runner/work/amp.dev/amp.dev/pages/extensions
        run: |
          python3 -m unittest discover -p "*_test.py"
