---
name: 'Test: Grow'

on:
  push:
    paths:
      - '*'
      # - 'pages/extensions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing Node.js packages
        run: npm ci

      - name: Preparing test resources
        run: |
          gulp buildComponentVersions
          npx run build:grow-tests

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Installing Grow
        run: pip install grow

      - name: Running Grow tests
        run: |
          cd pages/extensions
          python3 -m unittest discover -p \"*_test.py\"
